In [1]:
# ethereum price prediction - created in google colab

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [5]:
from google.colab import files
files.upload()

ModuleNotFoundError: No module named 'google.colab'

In [24]:
# get and show the data
df = pd.read_csv('ETH-USD1.csv')

#show the data
df

          Date         Open         High          Low        Close
0    5/19/2020   214.604935   214.604935   210.143051   213.451111
1    5/20/2020   213.446243   214.716827   207.975815   210.096741
2    5/21/2020   210.129150   211.625183   193.346436   199.883606
3    5/22/2020   199.837112   208.591537   198.040863   207.169189
4    5/23/2020   207.194489   210.386459   205.294220   208.694397
..         ...          ...          ...          ...          ...
361  5/15/2021  4075.951660  4129.185547  3638.122070  3638.122070
362  5/16/2021  3641.830811  3878.895996  3350.951660  3587.506104
363  5/17/2021  3581.343018  3587.765625  3129.008789  3282.397705
364  5/18/2021  3641.830811  3878.895996  3350.951660  3587.506104
365  5/19/2021  3370.115967  3437.935791  3364.048340  3364.048340

[366 rows x 5 columns]

In [25]:
# variable for predicting 'n' days out into future
projection = 14
# create a new column called 'prediction'
df['Prediction'] = df[['Close']].shift(-projection)
df

          Date         Open         High          Low        Close  Prediction
0    5/19/2020   214.604935   214.604935   210.143051   213.451111  237.219055
1    5/20/2020   213.446243   214.716827   207.975815   210.096741  244.179321
2    5/21/2020   210.129150   211.625183   193.346436   199.883606  244.426392
3    5/22/2020   199.837112   208.591537   198.040863   207.169189  241.221985
4    5/23/2020   207.194489   210.386459   205.294220   208.694397  241.931320
..         ...          ...          ...          ...          ...         ...
361  5/15/2021  4075.951660  4129.185547  3638.122070  3638.122070         NaN
362  5/16/2021  3641.830811  3878.895996  3350.951660  3587.506104         NaN
363  5/17/2021  3581.343018  3587.765625  3129.008789  3282.397705         NaN
364  5/18/2021  3641.830811  3878.895996  3350.951660  3587.506104         NaN
365  5/19/2021  3370.115967  3437.935791  3364.048340  3364.048340         NaN

[366 rows x 6 columns]

In [26]:
# create the independent dataset (x)
x = np.array(df[['Close']])
# remove the last rows 'nan'
x = x[:-projection]
print(X)

[[ 213.451111]
 [ 210.096741]
 [ 199.883606]
 [ 207.169189]
 [ 208.694397]
 [ 202.370346]
 [ 205.319748]
 [ 201.902313]
 [ 208.863434]
 [ 219.840424]
 [ 220.675125]
 [ 242.345596]
 [ 230.975708]
 [ 246.99176 ]
 [ 237.219055]
 [ 244.179321]
 [ 244.426392]
 [ 241.221985]
 [ 241.93132 ]
 [ 245.167252]
 [ 246.309906]
 [ 244.911453]
 [ 247.444946]
 [ 231.702667]
 [ 237.49321 ]
 [ 238.908844]
 [ 234.1147  ]
 [ 229.928909]
 [ 234.416168]
 [ 233.028275]
 [ 232.101166]
 [ 227.13829 ]
 [ 229.274261]
 [ 228.989822]
 [ 242.533188]
 [ 244.142151]
 [ 235.772461]
 [ 232.944489]
 [ 229.668045]
 [ 222.959793]
 [ 225.347168]
 [ 228.19487 ]
 [ 226.315002]
 [ 231.113419]
 [ 229.392197]
 [ 225.38707 ]
 [ 229.074112]
 [ 227.664597]
 [ 241.510223]
 [ 239.075531]
 [ 246.670013]
 [ 243.015961]
 [ 240.984985]
 [ 239.458176]
 [ 242.131699]
 [ 239.604584]
 [ 240.211487]
 [ 238.423523]
 [ 233.640884]
 [ 232.773087]
 [ 235.48381 ]
 [ 238.487518]
 [ 236.153168]
 [ 245.016724]
 [ 262.190643]
 [ 274.689056]
 [ 279.215424]
 [ 304.056763]
 [ 309.643616]
 [ 321.514099]
 [ 316.657257]
 [ 318.190887]
 [ 334.586639]
 [ 345.554657]
 [ 385.199707]
 [ 370.671722]
 [ 386.295166]
 [ 389.875488]
 [ 401.590576]
 [ 394.961945]
 [ 379.512848]
 [ 393.987366]
 [ 391.120453]
 [ 395.887573]
 [ 380.384064]
 [ 391.02417 ]
 [ 428.741791]
 [ 437.397827]
 [ 433.354919]
 [ 433.786621]
 [ 429.53125 ]
 [ 423.669312]
 [ 406.463776]
 [ 416.439789]
 [ 389.126343]
 [ 395.835144]
 [ 391.384491]
 [ 408.144196]
 [ 384.001038]
 [ 386.466125]
 [ 382.632629]
 [ 395.874664]
 [ 399.921478]
 [ 428.395721]
 [ 435.079742]
 [ 477.05191 ]
 [ 440.040497]
 [ 385.671936]
 [ 388.24115 ]
 [ 335.260071]
 [ 353.362274]
 [ 352.673492]
 [ 337.602112]
 [ 351.110016]
 [ 368.101898]
 [ 374.695587]
 [ 387.183105]
 [ 365.570007]
 [ 377.26886 ]
 [ 364.839203]
 [ 365.812286]
 [ 389.019226]
 [ 384.364532]
 [ 385.544373]
 [ 371.052826]
 [ 341.786072]
 [ 344.503174]
 [ 320.585541]
 [ 349.356659]
 [ 352.161865]
 [ 354.965271]
 [ 357.321686]
 [ 354.9505  ]
 [ 359.963409]
 [ 360.022369]
 [ 353.231293]
 [ 346.532654]
 [ 347.321594]
 [ 353.121918]
 [ 354.2771  ]
 [ 341.021149]
 [ 342.119781]
 [ 351.455658]
 [        nan]
 [ 370.96759 ]
 [ 375.142059]
 [        nan]
 [        nan]
 [ 379.484039]
 [ 377.441833]
 [ 366.229004]
 [ 368.855927]
 [ 378.213684]
 [ 379.935608]
 [ 369.136902]
 [ 392.189972]
 [ 413.77298 ]
 [ 409.766693]
 [ 412.457611]
 [ 406.217773]
 [ 393.888306]
 [ 403.99704 ]
 [ 388.650757]
 [ 386.730103]
 [ 382.819977]
 [ 386.590332]
 [ 396.358185]
 [ 383.156738]
 [ 387.602173]
 [ 402.141998]
 [ 414.067352]
 [ 454.719299]
 [ 435.713135]
 [ 453.554779]
 [ 444.163055]
 [ 449.679626]
 [ 462.960541]
 [ 461.00528 ]
 [ 474.626434]
 [ 460.149841]
 [ 447.559082]
 [ 459.940308]
 [ 480.360077]
 [ 479.48407 ]
 [ 471.630432]
 [ 509.744568]
 [ 549.486633]
 [ 558.068115]
 [ 608.454041]
 [ 603.897766]
 [ 570.686646]
 [ 518.801147]
 [ 517.493713]
 [ 538.229797]
 [ 575.758057]
 [ 614.842529]
 [ 587.324158]
 [ 598.352356]
 [ 616.70874 ]
 [ 569.354187]
 [ 596.595459]
 [ 601.908997]
 [ 591.843384]
 [ 554.827759]
 [ 573.479126]
 [ 559.678528]
 [ 545.797363]
 [ 568.567322]
 [ 589.663208]
 [ 586.011169]
 [ 589.355591]
 [ 636.181824]
 [ 642.868958]
 [ 654.811951]
 [ 659.297913]
 [ 638.290833]
 [ 609.817871]
 [ 634.854187]
 [ 583.7146  ]
 [ 611.607178]
 [ 626.410706]
 [ 635.835815]
 [ 682.642334]
 [ 730.397339]
 [ 731.520142]
 [ 751.618958]
 [ 737.803406]
 [ 730.367554]
 [ 774.534973]
 [ 975.50769 ]
 [1040.233032]
 [1100.006104]
 [1207.112183]
 [1225.678101]
 [1224.197144]
 [1281.077271]
 [1262.246704]
 [1090.145386]
 [1043.43457 ]
 [1130.73938 ]
 [1218.453003]
 [1171.834595]
 [1233.537598]
 [1230.172241]
 [1257.279541]
 [1377.295898]
 [1382.274048]
 [1121.570923]
 [1236.512207]
 [1230.990601]
 [1391.609375]
 [1324.414795]
 [1357.058105]
 [1253.187134]
 [1298.101807]
 [1382.522827]
 [1376.115479]
 [1314.986206]
 [1369.040527]
 [1515.193726]
 [1660.909546]
 [1594.762695]
 [1718.650879]
 [1677.846802]
 [1614.227783]
 [1746.616821]
 [1768.035034]
 [1744.243408]
 [1783.797974]
 [1843.532593]
 [1814.109863]
 [1805.084106]
 [1779.791016]
 [1781.067505]
 [1848.458252]
 [1937.449219]
 [1960.164795]
 [1919.534058]
 [1935.601074]
 [1781.99292 ]
 [1570.203979]
 [1626.575684]
 [1475.703735]
 [1446.033691]
 [1459.973145]
 [1416.04895 ]
 [1564.707642]
 [1492.608765]
 [1575.853149]
 [1541.914307]
 [1533.275024]
 [1654.741577]
 [1723.153809]
 [1834.727905]
 [1868.048828]
 [1799.16626 ]
 [1826.194946]
 [1772.102417]
 [1924.685425]
 [1854.564331]
 [1791.702271]
 [1806.971802]
 [1823.449341]
 [1782.855103]
 [1817.624146]
 [1812.634644]
 [1788.217041]
 [1691.333984]
 [1678.650146]
 [1593.413452]
 [1595.359253]
 [1702.842041]
 [1716.494629]
 [1691.355957]
 [1819.684937]
 [1846.033691]
 [1918.362061]
 [1977.276855]
 [2143.225586]
 [2028.422485]
 [2093.122803]
 [2107.887207]
 [2118.378906]
 [1971.077271]
 [2088.57373 ]
 [2072.108887]
 [2135.942139]
 [2157.656982]
 [2139.353271]
 [2299.187744]
 [2435.10498 ]
 [2519.116211]
 [2431.946533]
 [2344.89502 ]
 [2237.136963]
 [2166.188721]
 [2330.210938]
 [2364.751709]
 [2403.535156]
 [2363.586182]
 [2211.625732]
 [2316.05957 ]
 [2534.481689]
 [2662.865234]
 [2746.380127]
 [2756.876953]
 [2773.207031]
 [2945.892822]
 [2952.056152]
 [3431.086182]
 [3253.629395]
 [3522.783203]]

In [27]:
# create the dependent dataset (y)
y = df['Prediction'].values
y = y[:-projection]
print(y)

[ 237.219055  244.179321  244.426392  241.221985  241.93132   245.167252
  246.309906  244.911453  247.444946  231.702667  237.49321   238.908844
  234.1147    229.928909  234.416168  233.028275  232.101166  227.13829
  229.274261  228.989822  242.533188  244.142151  235.772461  232.944489
  229.668045  222.959793  225.347168  228.19487   226.315002  231.113419
  229.392197  225.38707   229.074112  227.664597  241.510223  239.075531
  246.670013  243.015961  240.984985  239.458176  242.131699  239.604584
  240.211487  238.423523  233.640884  232.773087  235.48381   238.487518
  236.153168  245.016724  262.190643  274.689056  279.215424  304.056763
  309.643616  321.514099  316.657257  318.190887  334.586639  345.554657
  385.199707  370.671722  386.295166  389.875488  401.590576  394.961945
  379.512848  393.987366  391.120453  395.887573  380.384064  391.02417
  428.741791  437.397827  433.354919  433.786621  429.53125   423.669312
  406.463776  416.439789  389.126343  395.835144  391.384491  408.144196
  384.001038  386.466125  382.632629  395.874664  399.921478  428.395721
  435.079742  477.05191   440.040497  385.671936  388.24115   335.260071
  353.362274  352.673492  337.602112  351.110016  368.101898  374.695587
  387.183105  365.570007  377.26886   364.839203  365.812286  389.019226
  384.364532  385.544373  371.052826  341.786072  344.503174  320.585541
  349.356659  352.161865  354.965271  357.321686  354.9505    359.963409
  360.022369  353.231293  346.532654  347.321594  353.121918  354.2771
  341.021149  342.119781  351.455658  351.455658  370.96759   375.142059
  379.935608  377.441833  379.484039  377.441833  366.229004  368.855927
  378.213684  379.935608  369.136902  392.189972  413.77298   409.766693
  412.457611  406.217773  393.888306  403.99704   388.650757  386.730103
  382.819977  386.590332  396.358185  383.156738  387.602173  402.141998
  414.067352  454.719299  435.713135  453.554779  444.163055  449.679626
  462.960541  461.00528   474.626434  460.149841  447.559082  459.940308
  480.360077  479.48407   471.630432  509.744568  549.486633  558.068115
  608.454041  603.897766  570.686646  518.801147  517.493713  538.229797
  575.758057  614.842529  587.324158  598.352356  616.70874   569.354187
  596.595459  601.908997  591.843384  554.827759  573.479126  559.678528
  545.797363  568.567322  589.663208  586.011169  589.355591  636.181824
  642.868958  654.811951  659.297913  638.290833  609.817871  634.854187
  583.7146    611.607178  626.410706  635.835815  682.642334  730.397339
  731.520142  751.618958  737.803406  730.367554  774.534973  975.50769
 1040.233032 1100.006104 1207.112183 1225.678101 1224.197144 1281.077271
 1262.246704 1090.145386 1043.43457  1130.73938  1218.453003 1171.834595
 1233.537598 1230.172241 1257.279541 1377.295898 1382.274048 1121.570923
 1236.512207 1230.990601 1391.609375 1324.414795 1357.058105 1253.187134
 1298.101807 1382.522827 1376.115479 1314.986206 1369.040527 1515.193726
 1660.909546 1594.762695 1718.650879 1677.846802 1614.227783 1746.616821
 1768.035034 1744.243408 1783.797974 1843.532593 1814.109863 1805.084106
 1779.791016 1781.067505 1848.458252 1937.449219 1960.164795 1919.534058
 1935.601074 1781.99292  1570.203979 1626.575684 1475.703735 1446.033691
 1459.973145 1416.04895  1564.707642 1492.608765 1575.853149 1541.914307
 1533.275024 1654.741577 1723.153809 1834.727905 1868.048828 1799.16626
 1826.194946 1772.102417 1924.685425 1854.564331 1791.702271 1806.971802
 1823.449341 1782.855103 1817.624146 1812.634644 1788.217041 1691.333984
 1678.650146 1593.413452 1595.359253 1702.842041 1716.494629 1691.355957
 1819.684937 1846.033691 1918.362061 1977.276855 2143.225586 2028.422485
 2093.122803 2107.887207 2118.378906 1971.077271 2088.57373  2072.108887
 2135.942139 2157.656982 2139.353271 2299.187744 2435.10498  2519.116211
 2431.946533 2344.89502  2237.136963 2166.188721 2330.210938 2364.751709
 2403.535156 2363.586182 2211.625732 2316.05957  2534.481689 2662.865234
 2746.380127 2756.876953 2773.207031 2945.892822 2952.056152 3431.086182
 3253.629395 3522.783203 3490.880371 3484.729004 3902.647705 3928.844727
 3952.293945 4168.701172 3785.848633 3715.148438 4079.057373 3638.12207
 3587.506104 3282.397705 3587.506104 3364.04834 ]

In [28]:
# split data into 85% training and 15% testing data sets
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = .15)

In [29]:
# create and train the model
linReg = LinearRegression()
# train the model
linReg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
# test the model using score 
linReg_confidence = linReg.score(x_test, y_test)
print('Linear regression Confidence:', linReg_confidence)

Linear regression Confidence: 0.9287423407739736

In [32]:
# create a variable called x_projection = last 14 rows of data from original dataset
x_projection = np.array(df[['Close']])[-projection:]
print(x_projection)

[[3490.880371]
 [3484.729004]
 [3902.647705]
 [3928.844727]
 [3952.293945]
 [4168.701172]
 [3785.848633]
 [3715.148438]
 [4079.057373]
 [3638.12207 ]
 [3587.506104]
 [3282.397705]
 [3587.506104]
 [3364.04834 ]]

In [34]:
# print linear regression model predictions for next 14 days
linReg_prediction = linReg.predict(x_projection)
print(linReg_prediction)

[4048.11712291 4040.96869716 4526.62673118 4557.06995894 4584.31999845
 4835.80409849 4390.8960076  4308.73620564 4731.63017404 4219.2248381
 4160.40466451 3805.84205493 4160.40466451 3900.72722464]